CREATE TABLE payments (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL,
    provider varchar(30) NOT NULL,
    provider_checkout_session_id varchar(255),
    provider_payment_intent_id varchar(255),
    amount numeric(10,2) NOT NULL,
    currency varchar(3) NOT NULL DEFAULT 'EUR',
    status varchar(30) NOT NULL DEFAULT 'PENDING',
    idempotency_key varchar(255),
    failure_code varchar(100),
    failure_message text,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT payments_order_id_fkey
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT payments_provider_check
        CHECK (provider IN ('STRIPE', 'PAYPAL')),

    CONSTRAINT payments_amount_check
        CHECK (amount > 0),

    CONSTRAINT payments_currency_check
        CHECK (currency = upper(currency)),

    CONSTRAINT payments_status_check
        CHECK (
            status IN (
                'PENDING',
                'PROCESSING',
                'PAID',
                'FAILED',
                'CANCELLED',
                'REFUNDED',
                'PARTIALLY_REFUNDED'
            )
        )
);

CREATE UNIQUE INDEX payments_provider_checkout_session_unique_idx
    ON payments(provider, provider_checkout_session_id)
    WHERE provider_checkout_session_id IS NOT NULL;

CREATE UNIQUE INDEX payments_provider_payment_intent_unique_idx
    ON payments(provider, provider_payment_intent_id)
    WHERE provider_payment_intent_id IS NOT NULL;

CREATE UNIQUE INDEX payments_idempotency_key_unique_idx
    ON payments(idempotency_key)
    WHERE idempotency_key IS NOT NULL;

CREATE INDEX payments_order_id_idx
    ON payments(order_id);

CREATE INDEX payments_status_idx
    ON payments(status);

CREATE TABLE payment_webhook_events (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    provider varchar(30) NOT NULL,
    provider_event_id varchar(255) NOT NULL,
    event_type varchar(150) NOT NULL,
    processed_at timestamp with time zone,
    created_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT payment_webhook_events_provider_check
        CHECK (provider IN ('STRIPE', 'PAYPAL')),

    CONSTRAINT payment_webhook_events_provider_event_unique
        UNIQUE (provider, provider_event_id)
);

CREATE INDEX payment_webhook_events_event_type_idx
    ON payment_webhook_events(event_type);
