CREATE TABLE inventory_reservations (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id integer NOT NULL,
    product_id integer NOT NULL,
    quantity integer NOT NULL,
    status varchar(20) NOT NULL DEFAULT 'RESERVED',
    reserved_at timestamp with time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    released_at timestamp with time zone,
    consumed_at timestamp with time zone,

    CONSTRAINT inventory_reservations_order_id_fkey
        FOREIGN KEY (order_id)
        REFERENCES orders(id)
        ON DELETE CASCADE,

    CONSTRAINT inventory_reservations_product_id_fkey
        FOREIGN KEY (product_id)
        REFERENCES products(id),

    CONSTRAINT inventory_reservations_quantity_check
        CHECK (quantity > 0),

    CONSTRAINT inventory_reservations_status_check
        CHECK (
            status IN (
                'RESERVED',
                'RELEASED',
                'CONSUMED'
            )
        ),

    CONSTRAINT inventory_reservations_released_at_check
        CHECK (
            status <> 'RELEASED'
            OR released_at IS NOT NULL
        ),

    CONSTRAINT inventory_reservations_consumed_at_check
        CHECK (
            status <> 'CONSUMED'
            OR consumed_at IS NOT NULL
        )
);

CREATE INDEX inventory_reservations_order_id_idx
    ON inventory_reservations(order_id);

CREATE INDEX inventory_reservations_product_id_idx
    ON inventory_reservations(product_id);

CREATE INDEX inventory_reservations_status_idx
    ON inventory_reservations(status);

CREATE UNIQUE INDEX inventory_reservations_order_product_active_unique_idx
    ON inventory_reservations(order_id, product_id)
    WHERE status = 'RESERVED';
